---

- name: Add key for nginx
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Add repo for Nginx
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'deb http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx'
    - 'deb-src http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx'

- name: Install Nginx
  apt: name=nginx update_cache=yes

- name: Copy Nginx config(nginx.conf) on remote host
  template: src=nginx/nginx.conf.j2
            dest=/etc/nginx/nginx.conf
            owner=root
            group=root
            mode=0644

- name: Copy Nginx default config on remote host
  template: src=nginx/default.conf.j2
            dest=/etc/nginx/conf.d/default.conf
            owner=root
            group=root
            mode=0644

- name: Adding fastcgi_params
  lineinfile: "dest=/etc/nginx/fastcgi_params line='fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;\n'"

- name: Copy fastcgi-php.conf config on remote host
  template: src=nginx/fastcgi-php.conf.j2
            dest=/etc/nginx/fastcgi-php.conf
            owner=root
            group=root
            mode=0644

- name: Create directory
  file: path={{ dir_for_web }} state=directory mode=0755

  notify:
    - Restart nginx


